// Auth
export const SET_FORM_ERROR = "SET_SIGNUP_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_IN_PROGRESS = "AUTH_IN_PROGRESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_IN_PROGRESS = "SIGNUP_IN_PROGRESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT"

// Profile
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_IN_PROGRESS = "GET_PROFILE_IN_PROGRESS"
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE"